### ISSUE TITLE
How to add created editor widget to Hello World Content Type

### ISSUE THREAD

**Issue by sunnythewebdeveloper** [h5p/h5p-editor-color-selector#3]
I have been following "Hello world tutorial"

I have created widget by following "How to create an editor widget" (https://github.com/h5p/h5p-editor-color-selector)

However I am unable add this widget tp content type and get this error 

Missing dependency H5PEditor.ColorSelector 1.0 required by H5P.GreetingCard 1.0.

How to add a custom widget to custom content type ?

Where to place the "H5PEditor.ColorSelector" so its accessable to "H5P.GreetingCard" in "drupal-7-69/sites/default/files/h5p/development" ?

![image](https://user-images.githubusercontent.com/64657118/80827030-aab17f00-8bfc-11ea-93aa-469565f6e0b8.png)

![image](https://user-images.githubusercontent.com/64657118/80827043-b00ec980-8bfc-11ea-8e41-6ba4a268eed3.png)

**Comment by otacke** [comment]
Hi sunnythewebdeveloper!

Yes, you will have to add your custom editor library (H5PEditor.ColorSelector in version 1.0) to the h5p/libraries folder or to the h5p/development folder if you are running the site in library development mode. Otherwise H5P can't load it.

Best,
Oliver

**Comment by sunnythewebdeveloper** [comment]
Hi otacke,

Thanks for the help got hint about version form your reply,
the devil was in details,
the tutorial at https://h5p.org/creating-editor-widgets
says to update H5P.GreetingCard/library.json with '"minorVersion": 0' for '"machineName": "H5PEditor.ColorSelector",'
but the version in https://github.com/h5p/h5p-editor-color-selector/library.json "minorVersion" is 3.

Hence it could not find "H5PEditor.ColorSelector" in "h5p/development"
just updated '"minorVersion": 3' in H5P.GreetingCard/library.json and all works.

Best Regards,
Sunny
